"""
core/interfaces.py (proposto) - Contratos Abstratos para Injeção de Dependencia.
Define os contratos que StateManager e EventBus devem implementar.
"""

from __future__ import annotations
from abc import ABC, abstractmethod
from typing import Any, Callable


class IStateManager(ABC):
    @abstractmethod
    def get(self, key: str, default: Any = None) -> Any: ...
    @abstractmethod
    def set(self, key: str, data: Any) -> None: ...
    @abstractmethod
    def delete(self, key: str) -> bool: ...
    @abstractmethod
    def keys(self) -> list[str]: ...
    @abstractmethod
    def exists(self, key: str) -> bool: ...
    @abstractmethod
    def close(self) -> None: ...


class IEventBus(ABC):
    @abstractmethod
    def subscribe(self, topic: str, handler: Callable) -> str: ...
    @abstractmethod
    def unsubscribe(self, topic: str, sub_id: str) -> bool: ...
    @abstractmethod
    async def publish(self, topic: str, data: Any = None, source: str = "") -> int: ...
    @abstractmethod
    def subscriber_count(self, topic: str) -> int: ...
    @abstractmethod
    def topics(self) -> list[str]: ...
    @abstractmethod
    def clear(self) -> int: ...
