"""initial

Revision ID: 88b186bfa6f3
Revises: 
Create Date: 2026-05-08 14:07:46.668806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88b186bfa6f3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portais',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('crawl_interval_hours', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('editais',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('portal_id', sa.Uuid(), nullable=False),
    sa.Column('titulo', sa.String(length=500), nullable=False),
    sa.Column('url_original', sa.String(length=1000), nullable=False),
    sa.Column('pdf_url', sa.String(length=1000), nullable=True),
    sa.Column('data_publicacao', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('requisitos_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('financiador', sa.String(length=300), nullable=True),
    sa.Column('valor_min', sa.Float(), nullable=True),
    sa.Column('valor_max', sa.Float(), nullable=True),
    sa.Column('moeda', sa.String(length=10), nullable=False),
    sa.Column('data_abertura', sa.DateTime(), nullable=True),
    sa.Column('data_encerramento', sa.DateTime(), nullable=True),
    sa.Column('eixos_tematicos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('perfil_elegivel', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mecanismo_financiamento', sa.String(length=200), nullable=True),
    sa.Column('abrangencia_geografica', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status_inscricao', sa.String(length=30), nullable=True),
    sa.Column('nivel_trl_min', sa.Integer(), nullable=True),
    sa.Column('nivel_trl_max', sa.Integer(), nullable=True),
    sa.Column('score_complexidade', sa.Integer(), nullable=True),
    sa.Column('resumo', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['portal_id'], ['portais.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url_original')
    )
    op.create_index(op.f('ix_editais_portal_id'), 'editais', ['portal_id'], unique=False)
    op.create_index(op.f('ix_editais_status'), 'editais', ['status'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('portal_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progresso', sa.Integer(), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=True),
    sa.Column('resultado', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('edital_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['edital_id'], ['editais.id'], ),
    sa.ForeignKeyConstraint(['portal_id'], ['portais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_portal_id'), 'jobs', ['portal_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_portal_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_editais_status'), table_name='editais')
    op.drop_index(op.f('ix_editais_portal_id'), table_name='editais')
    op.drop_table('editais')
    op.drop_table('portais')
    # ### end Alembic commands ###
