"""
Aletheia Architect Agent
Stage 1: Problem Analysis → Reasoning Phase Selection → Proof Skeleton Generation

Integrates:
- ReasoningOrchestrator-v11 (68 reasoning types, 7 phases)
- Domain-specific proof templates
- sequential-thinking MCP for reasoning transparency
- DecisionNode for strategy recording
"""

import json
from typing import Dict, List, Optional, Tuple
from dataclasses import dataclass
from datetime import datetime
import hashlib


@dataclass
class Problem:
    """Mathematical problem definition"""
    id: str
    domain: str  # algebra, logic, set_theory, analysis, etc.
    statement: str
    difficulty: str  # easy, intermediate, hard, research
    variables: List[str] = None
    

@dataclass
class ReasoningPlan:
    """Selected reasoning phases and strategies"""
    phases_selected: List[int]  # Phase 1-7
    reasoning_types: List[str]  # e.g., ["R01_Notation", "R02_Abstraction"]
    domain_strategy: str
    estimated_sorry_count: int


PHASE_DEFINITIONS = {
    1: {
        "name": "Foundational",
        "reasoning_types": ["R01_Notation", "R02_Abstraction", "R03_Decomposition"],
        "purpose": "Define notation, establish abstract concepts, decompose problem",
        "output": "Notation + abstraction layer + sub-problems"
    },
    2: {
        "name": "Inductive",
        "reasoning_types": ["R04_StructuralReduction", "R05_BaseCase", "R06_InductiveStep", "R07_Invariant"],
        "purpose": "Build inductive structure, establish base case, inductive step",
        "output": "Induction framework + base case proof"
    },
    3: {
        "name": "Deductive",
        "reasoning_types": ["R08_Lemma", "R09_Silogistic", "R10_BackwardChain"],
        "purpose": "Build lemmas, chain logical deductions",
        "output": "Lemma network + deductive proof tree"
    },
    4: {
        "name": "Constructive",
        "reasoning_types": ["R11_Witness", "R12_Recursive", "R13_Constructive"],
        "purpose": "Build witnesses, recursive structures, constructive proofs",
        "output": "Constructive witness + recursive definition"
    },
    5: {
        "name": "Refutational",
        "reasoning_types": ["R14_Contradiction", "R15_Counterexample"],
        "purpose": "Detect contradictions, find edge cases via counterexamples",
        "output": "Contradiction detection + edge case analysis"
    },
    6: {
        "name": "Verificational",
        "reasoning_types": ["R16_Dimensional", "R17_Algebraic", "R18_Counterexample"],
        "purpose": "Verify via Cora-Debate verifiers (V1, V2, V3)",
        "output": "Dimensional validity + algebraic consistency + counterexample-free"
    },
    7: {
        "name": "Meta-Cognitive",
        "reasoning_types": ["R19_ProofHealth", "R20_MetaAnalysis"],
        "purpose": "Check proof structure health, meta-level analysis",
        "output": "Proof health score + improvement suggestions"
    }
}

DOMAIN_STRATEGIES = {
    "set_theory": {
        "phases": [1, 2, 3, 5, 6, 7],  # Foundational→Inductive→Deductive→Refutational→Verificational→Meta
        "template": "proof_set_theory.template",
        "key_concepts": ["cardinality", "subset", "union", "intersection", "powerset"],
        "typical_sorry_count": 1
    },
    "algebra": {
        "phases": [1, 2, 3, 4, 6, 7],  # Foundational→Inductive→Deductive→Constructive→Verificational→Meta
        "template": "proof_algebra.template",
        "key_concepts": ["group", "ring", "field", "homomorphism", "isomorphism"],
        "typical_sorry_count": 1
    },
    "logic": {
        "phases": [1, 3, 5, 6, 7],  # Foundational→Deductive→Refutational→Verificational→Meta
        "template": "proof_logic.template",
        "key_concepts": ["proposition", "predicate", "quantifier", "proof", "validity"],
        "typical_sorry_count": 1
    },
    "analysis": {
        "phases": [1, 2, 3, 4, 5, 6, 7],  # All phases for continuous structures
        "template": "proof_analysis.template",
        "key_concepts": ["limit", "continuity", "differentiability", "integration"],
        "typical_sorry_count": 2  # More complex
    },
    "number_theory": {
        "phases": [1, 2, 3, 5, 6, 7],  # Foundational→Inductive→Deductive→Refutational→Verificational→Meta
        "template": "proof_number_theory.template",
        "key_concepts": ["prime", "divisibility", "congruence", "modular"],
        "typical_sorry_count": 1
    }
}

PROOF_TEMPLATES = {
    "proof_set_theory.template": """
theorem {theorem_name} : {statement} := by
  -- Reasoning Plan: {reasoning_phases}
  -- Proof structure generated by ReasoningOrchestrator v11 (Architect Agent)
  
  -- Phase 1: Foundational - Establish notation and abstraction
  {phase_1_abstraction}
  
  -- Phase 2: Inductive - Build inductive structure if needed
  {phase_2_induction}
  
  -- Phase 3: Deductive - Chain logical deductions
  {phase_3_deduction}
  
  -- Phase 5: Refutational - Handle edge cases
  {phase_5_refutation}
  
  -- Phase 6: Verificational - Verify with Cora-Debate
  {phase_6_verification}
  
  sorry
""",
    "proof_algebra.template": """
theorem {theorem_name} : {statement} := by
  -- Reasoning Plan: {reasoning_phases}
  -- Domain: Algebra (Group/Ring/Field structures)
  
  -- Phase 1: Foundational - Define group/ring structure
  {phase_1_abstraction}
  
  -- Phase 2: Inductive - Inductive properties if applicable
  {phase_2_induction}
  
  -- Phase 4: Constructive - Construct witness/homomorphism
  {phase_4_constructive}
  
  sorry
""",
    "proof_logic.template": """
theorem {theorem_name} : {statement} := by
  -- Reasoning Plan: {reasoning_phases}
  -- Domain: Mathematical Logic
  
  -- Phase 1: Foundational - Define propositions
  {phase_1_abstraction}
  
  -- Phase 3: Deductive - Logical deduction chain
  {phase_3_deduction}
  
  -- Phase 5: Refutational - Prove by contradiction
  {phase_5_refutation}
  
  sorry
"""
}


class ArchitectAgent:
    """Architect Agent: Analyzes problems and generates proof skeletons"""
    
    def __init__(self, reasoning_orchestrator=None, decision_node=None):
        """
        Initialize Architect Agent
        
        Args:
            reasoning_orchestrator: ReasoningOrchestrator-v11 instance
            decision_node: DecisionNode MCP client
        """
        self.reasoning_orchestrator = reasoning_orchestrator
        self.decision_node = decision_node
        self.generated_proofs = []
    
    def analyze(self, problem: Problem) -> Tuple[ReasoningPlan, Dict]:
        """
        Analyze problem and select reasoning phases
        
        Returns:
            (ReasoningPlan, metadata)
        """
        
        # Step 1: Classify domain
        domain_lower = problem.domain.lower()
        if domain_lower not in DOMAIN_STRATEGIES:
            domain_lower = "algebra"  # Default
        
        domain_strategy = DOMAIN_STRATEGIES[domain_lower]
        
        # Step 2: Select phases based on domain
        phases_selected = domain_strategy["phases"]
        
        # Step 3: Map to reasoning types
        reasoning_types = []
        for phase_num in phases_selected:
            if phase_num in PHASE_DEFINITIONS:
                reasoning_types.extend(PHASE_DEFINITIONS[phase_num]["reasoning_types"][:3])  # Top 3 per phase
        
        # Step 4: Create reasoning plan
        plan = ReasoningPlan(
            phases_selected=phases_selected,
            reasoning_types=reasoning_types,
            domain_strategy=domain_lower,
            estimated_sorry_count=domain_strategy["typical_sorry_count"]
        )
        
        # Step 5: Record decision
        if self.decision_node:
            self.decision_node.record_decision(
                id=f"proof-strategy-{problem.id}",
                decision=f"Phase selection: {phases_selected}",
                rationale=f"Domain {domain_lower} uses phases {phases_selected} for {problem.difficulty} difficulty"
            )
        
        return plan, {
            "domain": domain_lower,
            "difficulty": problem.difficulty,
            "phases_count": len(phases_selected),
            "reasoning_types_count": len(reasoning_types)
        }
    
    def generate_skeleton(self, problem: Problem, plan: ReasoningPlan) -> Dict:
        """
        Generate proof skeleton using template
        
        Returns:
            Proof structure with sorry blocks
        """
        
        template_name = DOMAIN_STRATEGIES[plan.domain_strategy]["template"]
        template = PROOF_TEMPLATES.get(template_name, PROOF_TEMPLATES["proof_algebra.template"])
        
        # Generate theorem name from problem ID
        theorem_name = f"theorem_{problem.id.replace(':', '_')}"
        
        # Build proof with phase annotations
        proof_code = template.format(
            theorem_name=theorem_name,
            statement=problem.statement,
            reasoning_phases=plan.phases_selected,
            phase_1_abstraction=f"-- Notation: {PHASE_DEFINITIONS[1]['purpose']}" if 1 in plan.phases_selected else "",
            phase_2_induction=f"-- Induction: {PHASE_DEFINITIONS[2]['purpose']}" if 2 in plan.phases_selected else "",
            phase_3_deduction=f"-- Deduction: {PHASE_DEFINITIONS[3]['purpose']}" if 3 in plan.phases_selected else "",
            phase_4_constructive=f"-- Witness: {PHASE_DEFINITIONS[4]['purpose']}" if 4 in plan.phases_selected else "",
            phase_5_refutation=f"-- Cases: {PHASE_DEFINITIONS[5]['purpose']}" if 5 in plan.phases_selected else "",
            phase_6_verification=f"-- Verify: {PHASE_DEFINITIONS[6]['purpose']}" if 6 in plan.phases_selected else "",
            phase_7_metacognitive=f"-- Health: {PHASE_DEFINITIONS[7]['purpose']}" if 7 in plan.phases_selected else "",
        )
        
        # Create proof object
        proof_obj = {
            "problem_id": problem.id,
            "domain": plan.domain_strategy,
            "statement": problem.statement,
            "lean_code": proof_code,
            "theorem_name": theorem_name,
            "reasoning_phases": plan.phases_selected,
            "reasoning_types": plan.reasoning_types,
            "estimated_sorry_count": plan.estimated_sorry_count,
            "confidence": 0.5 + (len(plan.phases_selected) / 7) * 0.3,  # Confidence score
            "generation_method": "architect_agent",
            "timestamp": datetime.now().isoformat(),
            "metadata": {
                "domain_strategy": plan.domain_strategy,
                "template_used": template_name,
                "phases_count": len(plan.phases_selected)
            }
        }
        
        self.generated_proofs.append(proof_obj)
        return proof_obj
    
    def process(self, problem: Problem) -> Dict:
        """
        Full pipeline: Analyze → Generate Skeleton
        
        Returns:
            Complete proof skeleton with reasoning plan
        """
        print(f"\n[Architect] Processing: {problem.id}")
        
        # Step 1: Analyze
        plan, metadata = self.analyze(problem)
        print(f"  Phase selection: {plan.phases_selected}")
        print(f"  Reasoning types: {len(plan.reasoning_types)}")
        
        # Step 2: Generate skeleton
        proof = self.generate_skeleton(problem, plan)
        print(f"  Generated proof skeleton (sorry_count: {proof['estimated_sorry_count']})")
        
        return {
            "problem_id": problem.id,
            "reasoning_plan": plan.__dict__,
            "proof": proof,
            "metadata": metadata
        }


def architect_run_example():
    """Example: Run architect on sample problems"""
    
    agent = ArchitectAgent()
    
    # Sample problems
    problems = [
        Problem(
            id="A0004",
            domain="set_theory",
            statement="For finite set S with n elements, |P(S)| = 2^n",
            difficulty="intermediate"
        ),
        Problem(
            id="B0014",
            domain="algebra",
            statement="Every finite group of prime order is cyclic",
            difficulty="intermediate"
        ),
        Problem(
            id="L0001",
            domain="logic",
            statement="If P → Q and P are both true, then Q is true (Modus Ponens)",
            difficulty="easy"
        )
    ]
    
    results = []
    for problem in problems:
        result = agent.process(problem)
        results.append(result)
        print(f"\nGenerated proof skeleton:")
        print(result["proof"]["lean_code"][:300] + "...")
    
    return results


if __name__ == "__main__":
    results = architect_run_example()
    print("\n" + "="*60)
    print(f"Architect Agent: Generated {len(results)} proof skeletons")
    print("="*60)
    
    # Save results
    with open("architect_results.json", "w", encoding="utf-8") as f:
        json.dump(results, f, indent=2)
    print("Results saved to architect_results.json")
